let a =10;
console.log("hello")
try{
    console.log(A)
} catch(Error){
    console.log("Error in this section")
    console.log(Error)
}